import Head from 'next/head';

const Home = () => {
  return (
    <div>
      <Head>
        <title>Young Dev</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>Welcome in new project!</h1>
    </div>
  );
};

export default Home;
